# Generated by Django 3.2.8 on 2021-10-26 13:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='man.png', upload_to=blog.models.upload_image_path),
        ),
    ]
