# Generated by Django 3.2.8 on 2021-10-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
