# Generated by Django 3.2.8 on 2021-10-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211028_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='blog.IPAddress'),
        ),
    ]
