# Generated by Django 3.2.8 on 2021-10-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_product_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ip_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ipaddress'),
        ),
    ]
