# Generated by Django 3.2.8 on 2021-10-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_customer_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ip_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
