# Generated by Django 3.2.8 on 2021-10-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.coupon'),
        ),
    ]
